---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-14.04
  driver:
    network:
    - ["forwarded_port", {guest: 8080, host: 9001}]
    - ["private_network", {ip: "192.168.33.34"}]
- name: centos-6.5
  driver:
    network:
    - ["forwarded_port", {guest: 8080, host: 9000}]
    - ["private_network", {ip: "192.168.33.33"}]

suites:
- name: playframework
#  encrypted_data_bag_secret_key_path: <%= ENV['ENCRYPTED_DATA_BAG_SECRET'] %>
#  data_bags_path: <%= ENV['MERLE'] %>/data_bags
  run_list: ["recipe[playframework_test::default]"]
  attributes: {
    "playframework": {
      "app_conf": {
        "secret": "mysecret"
      },
      "app_args": [
        "-Dhttp.port=8080",
        "-J-Xms128M",
        "-J-Xmx512m",
        "-J-server"
      ]
    },
    "java": {
      "jdk_version": "7",
      "install_flavor": "oracle",
      "oracle": {
        "accept_oracle_download_terms": "true"
      },
      "jdk": {
        "7": {
          "x86_64": {
            "url": "https://s3.amazonaws.com/prsnpublic/jdk-7u45-linux-x64.tar.gz"
          }
        }
      }
    }
  }
